Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3

Lint/AssignmentInCondition:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '[]'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'
Documentation:
    Enabled: false
